# Server Port
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/coalmine_db
spring.datasource.username=root
spring.datasource.password=newuser1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect